apiVersion: v1
kind: Service
metadata:
  app: hello-python1
  k8s-app: hello-python1
  name: hello-python1
spec:
  selector:
    app: hello-python1
  ports:
  - name: http
    protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python1
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-python1
  template:
    metadata:
      labels:
        app: hello-python1
    spec:
      containers:
      - name: hello-python1
        image: phanick/hello-python1:5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
